# Generated by Django 3.0.6 on 2020-05-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateField()),
                ('feeling', models.TextField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_app.Habit')),
            ],
        ),
    ]
