# Generated by Django 3.0.6 on 2020-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='rating',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
